extra-deps:
  - yesod-auth-oauth-1.4.1.1
    # ETH login via LDAP
  - yesod-auth-ldap-native-0.2.0.0
  - ldap-client-0.1.0
    # LTI interop client
  - ltiv1p1-1.0.0.3
    # better documentation
  - superdoc-0.1.2.4
    # resolve symlinks
  - directory-1.3.1.0

flags: {}

packages:
  - .
  - location: ../../../libs/hs/luci-connect
    extra-dep: true
  - location: ../../../libs/hs/qua-types
    extra-dep: true
resolver: lts-8.21
require-stack-version: ">= 1.1.0"
extra-package-dbs: []
